import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { detectProject } from './detectors/index.js';

const ATS_CONFIG_FILE = '.ats.yml';

function buildYaml(projectPath: string): string {
  const ctx = detectProject(projectPath);

  const types = ctx.types.join(', ') || 'unknown';
  const pm = ctx.packageManager ?? 'npm';

  const skipGates: string[] = ['performance'];
  if (!ctx.types.includes('react') && !ctx.types.includes('nodejs')) {
    skipGates.push('e2e', 'ui-behavior', 'a11y');
  }
  if (!ctx.types.includes('python')) {
    // no python-specific skips needed — gates auto-detect
  }

  const skipBlock = skipGates.map((g) => `    - ${g}`).join('\n');
  const hasWeb = ctx.types.includes('react') || ctx.types.includes('nodejs');

  const a11yNote = hasWeb
    ? '  # a11y: install @axe-core/playwright and add tests tagged "a11y" to enable'
    : '';

  return `# ATS configuration — generated by \`ats init\`
# Detected project type: ${types}
# Package manager: ${pm}
# Edit this file to customize your gate pipeline.

gates:
  skip:
${skipBlock}
  # Add other gates to skip, e.g.: lint, typecheck, tests, build, audit, ci-config, e2e, security, ui-behavior, a11y
${a11yNote}

report:
  dir: ./reports

fail-fast: true
include-perf: false
`;
}

export interface InitResult {
  configPath: string;
  skipped: boolean;
  content: string;
}

export function initProject(projectPath: string, force = false): InitResult {
  const absPath = resolve(projectPath);
  mkdirSync(absPath, { recursive: true });
  const configPath = join(absPath, ATS_CONFIG_FILE);

  if (existsSync(configPath) && !force) {
    const existing = readFileSync(configPath, 'utf-8');
    return { configPath, skipped: true, content: existing };
  }

  const content = buildYaml(absPath);
  writeFileSync(configPath, content, 'utf-8');
  return { configPath, skipped: false, content };
}
